#! /usr/bin/env bash

echo "Welcome! Let's bild you derivation!"
echo -n -e "\e[36m> What do you want to call your derivation?\e[0m " && read NAME
echo -n -e "\e[36m> Where can I find the dmg file?\e[0m " && read LOCATION

# Get the sha256
SHA=$(nix-prefetch-url "$LOCATION")

# The temporary output file
OUT_FILE="/tmp/$SHA-$NAME.nix"

cat <<EOF >> /tmp/$SHA-derivation.nix
{ pkgs ? import <nixpkgs> {}, ... }:
stdenv.mkDerivation rec {
  name = "$NAME";
  buildInputs = [ undmg ];
  sourceRoot = ".";
  phases = [ "unpackPhase" "installPhase" ];

  # Just move the .app folder to local Applications
  installPhase = ''
    mkdir -p "\$out/Applications"
    cp -r Firefox.app "\$out/Applications"
  '';

  src = fetchurl {
    name = "\${name}.dmg";
    url = "$LOCATION";
    sha256 = "$SHA";
  };
}
EOF

echo "The derivation was generated to $OUT_FILE!"
echo "Install it with \`nix-env -i -f $OUT_FILE\` or move it to your derivations folder."
