#! /usr/bin/env fish

# Test if signed in
op list users 2> /dev/null

while [ $status = 1 ]
    eval (op signin my)
end

op list items --categories Login | jq '.[] | .overview.title' \
    | tr -d \" | fzf | op get item - --fields password | pbcopy
