#!/bin/zsh

help() {
    echo "Usage: record [--screen] [--title TITLE] OUTPUT"
    echo "You can specify the output format with the file extension."
    exit 1
}

rec() {
    echo -e -n "Recording ... [q] to stop.\r"
    if [[ -n "$1" ]]; then
        ffmpeg -f avfoundation -i "1" "$1" 2> /dev/null
    else
        if [[ -f "/tmp/output.gif" ]]; then
            rm /tmp/output.gif
        fi
        ffmpeg -f avfoundation -i "1" "/tmp/output.gif" 2> /dev/null
    fi
}

crop() {
    # Extract info
    window=$(yabai -m query --windows | jq '.[] | select(.app=="kitty")')
    if [[ -n "$1" ]]; then
        window=$(yabai -m query --windows | jq ".[] | select(.tile==\"$1\")")
    fi
    x=$(expr $(echo $window | jq '.frame | .x') \* 2 \- 8)
    y=$(expr $(echo $window | jq '.frame | .y') \* 2 \- 8)
    w=$(expr $(echo $window | jq '.frame | .w') \* 2 \+ 16)
    h=$(expr $(echo $window | jq '.frame | .h') \* 2 \+ 16)

    echo -e -n "Cropping '$file' ... [q] to abort.\r"
    ffmpeg -i /tmp/output.gif -vf "crop=${w}:${h}:${x}:${y}" "$file" 2> /dev/null
    rm /tmp/output.gif
}

if [ ! -n "$1" ]; then
    help
    exit 1
fi

file=${@[-1]}
if [[ -f "$file" ]]; then
    echo "File already exists! Aborting ..."
    exit 1
fi

case "$1" in
    $file)
        rec
        crop
        ;;
    "-s" | "--screen")
        rec "$file"
        ;;
    "-t" | "--title")
        if [[ ! -n "$2" ]] || [[ "$2" == "$file" ]]; then
            help
        fi
        rec
        crop "$2"
        ;;
    *)
        help
        exit 1
        ;;
esac

echo "Finished! GIF file can be found at '$file'."
