#!/bin/bash

service="airdrop"
if [[ -n "$2" ]]; then
    service="$2"
fi

if [[ "$1" == /* ]]; then
    url="file://$1"
else
    url="file://$(pwd)/$1"
fi

/Applications/terminal-share.app/Contents/MacOS/terminal-share -service $service -url $url
