#!/bin/bash

STUNPORT=19302
STUNSERVER="stun1.l.google.com"

# turnutils_stunclient from "coturn" package
function with_tool {
    turnutils_stunclient -p $STUNPORT $STUNSERVER | awk 'NF > 1 { print $NF }' | sed 's/:.*//'
}

# Manually
function manual {
    LISTENPORT=20000
    MESSAGE="\x00\x01\x00\x00YOGO\x59\x4f\x47\x4fSTACFLOW"
    # Send UPD packet
    echo -ne "$MESSAGE" | nc -u -p $LISTENPORT $STUNSERVER $STUNPORT -w 0
    # Receive response and extract info
    timeout 1 nc -l -u $LISTENPORT | head -c 32 | tail -c 4 | hexdump -e '/1 "%u" "."' | grep -o ".*[^.]" || echo "Err: failed, damn it!"
}

with_tool
